# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libzmq3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew update && sudo brew uninstall --force zeromq && sudo brew cleanup --force -s zeromq && sudo brew prune; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo brew install zeromq; fi

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
