# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libzmq3-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew link zeromq; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install zeromq; fi

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
