# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
#  - osx

compiler:
  - gcc
#  - clang

addons:
  apt:
  packages:
  - r-cran-rmpi r-cran-rsprng mpi-default-dev
#
# before_install:
#   - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo chmod -R a+w /usr/local/Cellar; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew uninstall --force zeromq && brew cleanup --force -s zeromq && brew prune; fi
# - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link zeromq && brew install zeromq; fi

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'
